export const movies = [
    {
        adult: false,
        backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
        id: 438695,
        original_language: "en",
        original_title: "Sing 2",
        overview: "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
        popularity: 9211.33,
        poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
        release_date: "2021-12-01",
        title: "Sing 2",
        video: false,
        vote_average: 7.5,
        vote_count: 264,
    },
    {
        adult: false,
        backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
        id: 425909,
        original_language: "en",
        original_title: "Ghostbusters: Afterlife",
        overview: "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
        popularity: 7227.726,
        poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
        release_date: "2021-11-11",
        title: "Ghostbusters: Afterlife",
        video: false,
        vote_average: 7.2,
        vote_count: 753,
    },
    {
        adult: false,
        backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
        id: 634649,
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        popularity: 6708.051,
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        release_date: "2021-12-15",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 8.4,
        vote_count: 4020,
    },
    {
        adult: false,
        backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
        id: 568124,
        original_language: "en",
        original_title: "Encanto",
        overview: "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
        popularity: 6071.14,
        poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
        release_date: "2021-11-24",
        title: "Encanto",
        video: false,
        vote_average: 7.8,
        vote_count: 2616,
    },
    {
        adult: false,
        backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
        genre_ids: (3)[27, 28, 878],
        id: 460458,
        original_language: "en",
        original_title: "Resident Evil: Welcome to Raccoon City",
        overview: "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
        popularity: 5449.78,
        poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
        release_date: "2021-11-24",
        title: "Resident Evil: Welcome to Raccoon City",
        video: false,
        vote_average: 6,
        vote_count: 824,
    },
    {
        adult: false,
        backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
        id: 624860,
        original_language: "en",
        original_title: "The Matrix Resurrections",
        overview: "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
        popularity: 4189.812,
        poster_path: "/gZlZLxJMfnSeS60abFZMh1IvODQ.jpg",
        release_date: "2021-12-16",
        title: "The Matrix Resurrections",
        video: false,
        vote_average: 7,
        vote_count: 2056,
    },
    {
        adult: false,
        backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
        genre_ids: (3)[878, 28, 12],
        id: 580489,
        original_language: "en",
        original_title: "Venom: Let There Be Carnage",
        overview: "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        popularity: 3458.355,
        poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
        release_date: "2021-09-30",
        title: "Venom: Let There Be Carnage",
        video: false,
        vote_average: 7.2,
        vote_count: 5749,
    }
]

export const detail = [
    {
        adult: false,
        backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
        belongs_to_collection: { id: 544670, name: 'Sing Collection', poster_path: '/h151oRzvsxfKRznEmlQJRlnvsid.jpg', backdrop_path: '/z9ft5HYHzWcasR6SGcgeluxTznB.jpg' },
        budget: 85000000,
        genres: [
            { id: 16, name: 'Animation' }
            , { id: 35, name: 'Comedy' }
            , { id: 10751, name: 'Family' }
            , { id: 10402, name: 'Music' }
        ],
        homepage: "https://www.illumination.com/movie/sing-2/",
        id: 438695,
        imdb_id: "tt6467266",
        original_language: "en",
        original_title: "Sing 2",
        overview: "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
        popularity: 9211.33,
        poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
        release_date: "2021-12-01",
        revenue: 190860000,
        runtime: 110,
        tagline: "Where will your dreams take you?",
        title: "Sing 2",
        video: false,
        vote_average: 7.6,
        vote_count: 310,
    },
    {
        adult: false,
        backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
        belongs_to_collection: { id: 2980, name: 'Ghostbusters Collection', poster_path: '/sctvCtE1M1rDF4f0W2fMrk2BrGB.jpg', backdrop_path: '/6Jnlhr2ac8OuDJEowsFLzZY3SXd.jpg' },
        budget: 75000000,
        genres: [
            , { id: 35, name: 'Comedy' }
            , { id: 14, name: 'Fantasy' }
            , { id: 12, name: 'Adventure' }],
        homepage: "https://ghostbusters.com/",
        id: 425909,
        imdb_id: "tt4513678",
        original_language: "en",
        original_title: "Ghostbusters: Afterlife",
        overview: "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
        popularity: 7227.726,
        poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
        release_date: "2021-11-11",
        revenue: 191000000,
        runtime: 124,
        status: "Released",
        tagline: "Discover the past. Protect the future.",
        title: "Ghostbusters: Afterlife",
        video: false,
        vote_average: 7.2,
        vote_count: 773,
    },
    {
        adult: false,
        backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
        belongs_to_collection: { id: 531241, name: 'Spider-Man (Avengers) Collection', poster_path: '/nogV4th2P5QWYvQIMiWHj4CFLU9.jpg', backdrop_path: '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg' },
        budget: 200000000,
        genres: [

            , { id: 28, name: 'Action' }
            , { id: 12, name: 'Adventure' }
            , { id: 878, name: 'Science Fiction' }
        ],
        homepage: "https://www.spidermannowayhome.movie",
        id: 634649,
        imdb_id: "tt10872600",
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        popularity: 6708.051,
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        release_date: "2021-12-15",
        revenue: 1538282364,
        runtime: 148,
        status: "Released",
        tagline: "The Multiverse unleashed.",
        title: "Spider-Man: No Way Home",
        video: false,
        vote_average: 8.4,
        vote_count: 4037,
    },
    {
        adult: false,
        backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
        belongs_to_collection: null,
        budget: 50000000,
        genres: [

            , { id: 16, name: 'Animation' }
            , { id: 35, name: 'Comedy' }
            , { id: 10751, name: 'Family' }
            , { id: 14, name: 'Fantasy' }
        ],
        homepage: "https://movies.disney.com/encanto",
        id: 568124,
        imdb_id: "tt2953050",
        original_language: "en",
        original_title: "Encanto",
        overview: "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
        popularity: 6071.14,
        poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
        release_date: "2021-11-24",
        revenue: 215000000,
        runtime: 102,
        status: "Released",
        tagline: "There's a little magic in all of us ...almost all of us.",
        title: "Encanto",
        video: false,
        vote_average: 7.8,
        vote_count: 2645,
    },
    {
        adult: false,
        backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
        belongs_to_collection: null,
        budget: 40000000,
        genres: [

            , { id: 27, name: 'Horror' }
            , { id: 28, name: 'Action' }
            , { id: 878, name: 'Science Fiction' }
        ],
        homepage: "https://www.residentevil.movie",
        id: 460458,
        imdb_id: "tt6920084",
        original_language: "en",
        original_title: "Resident Evil: Welcome to Raccoon City",
        overview: "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
        popularity: 5449.78,
        poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
        release_date: "2021-11-24",
        revenue: 31000000,
        runtime: 107,
        status: "Released",
        tagline: "Witness the beginning of evil.",
        title: "Resident Evil: Welcome to Raccoon City",
        video: false,
        vote_average: 6,
        vote_count: 830,
    },
    {
        adult: false,
        backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
        belongs_to_collection: { id: 2344, name: 'The Matrix Collection', poster_path: '/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg', backdrop_path: '/bRm2DEgUiYciDw3myHuYFInD7la.jpg' },
        budget: 190000000,
        genres: [

            , { id: 878, name: 'Science Fiction' }
            , { id: 28, name: 'Action' }
            , { id: 12, name: 'Adventure' }
        ],
        homepage: "https://www.whatisthematrix.com",
        id: 624860,
        imdb_id: "tt10838180",
        original_language: "en",
        original_title: "The Matrix Resurrections",
        overview: "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
        popularity: 4189.812,
        poster_path: "/gZlZLxJMfnSeS60abFZMh1IvODQ.jpg",
        release_date: "2021-12-16",
        revenue: 124000000,
        runtime: 148,
        status: "Released",
        tagline: "Return to the source.",
        title: "The Matrix Resurrections",
        video: false,
        vote_average: 7,
        vote_count: 2071,
    },
    {
        adult: false,
        backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
        belongs_to_collection: { id: 558216, name: 'Venom Collection', poster_path: '/670x9sf0Ru8y6ezBggmYudx61yB.jpg', backdrop_path: '/rhLspFB1B8ZCkWEHFYmc3NKagzq.jpg' },
        budget: 110000000,
        genres: [

            , { id: 878, name: 'Science Fiction' }
            , { id: 28, name: 'Action' }
            , { id: 12, name: 'Adventure' }
        ],
        homepage: "https://www.venom.movie",
        id: 580489,
        imdb_id: "tt7097896",
        original_language: "en",
        original_title: "Venom: Let There Be Carnage",
        overview: "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        popularity: 3458.355,
        poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
        release_date: "2021-09-30",
        revenue: 500000000,
        runtime: 97,
        status: "Released",
        tagline: "",
        title: "Venom: Let There Be Carnage",
        video: false,
        vote_average: 7.2,
        vote_count: 5755,
    }
]